/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing AssociationSpec
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssociationSpecTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssociationSpec
        //private AssociationSpec instance;

        public AssociationSpecTests()
        {
            // TODO uncomment below to create an instance of AssociationSpec
            //instance = new AssociationSpec();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssociationSpec
        /// </summary>
        [Fact]
        public void AssociationSpecInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssociationSpec
            //Assert.IsType<AssociationSpec>(instance);
        }

        /// <summary>
        /// Test the property 'AssociationCategory'
        /// </summary>
        [Fact]
        public void AssociationCategoryTest()
        {
            // TODO unit test for the property 'AssociationCategory'
        }

        /// <summary>
        /// Test the property 'AssociationTypeId'
        /// </summary>
        [Fact]
        public void AssociationTypeIdTest()
        {
            // TODO unit test for the property 'AssociationTypeId'
        }
    }
}
