/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing BatchInputSimplePublicObjectBatchInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchInputSimplePublicObjectBatchInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchInputSimplePublicObjectBatchInput
        //private BatchInputSimplePublicObjectBatchInput instance;

        public BatchInputSimplePublicObjectBatchInputTests()
        {
            // TODO uncomment below to create an instance of BatchInputSimplePublicObjectBatchInput
            //instance = new BatchInputSimplePublicObjectBatchInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchInputSimplePublicObjectBatchInput
        /// </summary>
        [Fact]
        public void BatchInputSimplePublicObjectBatchInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchInputSimplePublicObjectBatchInput
            //Assert.IsType<BatchInputSimplePublicObjectBatchInput>(instance);
        }

        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Fact]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
    }
}
