/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing BatchResponseSimplePublicObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchResponseSimplePublicObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchResponseSimplePublicObject
        //private BatchResponseSimplePublicObject instance;

        public BatchResponseSimplePublicObjectTests()
        {
            // TODO uncomment below to create an instance of BatchResponseSimplePublicObject
            //instance = new BatchResponseSimplePublicObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchResponseSimplePublicObject
        /// </summary>
        [Fact]
        public void BatchResponseSimplePublicObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchResponseSimplePublicObject
            //Assert.IsType<BatchResponseSimplePublicObject>(instance);
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

        /// <summary>
        /// Test the property 'RequestedAt'
        /// </summary>
        [Fact]
        public void RequestedAtTest()
        {
            // TODO unit test for the property 'RequestedAt'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
