/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing CollectionResponseAssociatedId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionResponseAssociatedIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionResponseAssociatedId
        //private CollectionResponseAssociatedId instance;

        public CollectionResponseAssociatedIdTests()
        {
            // TODO uncomment below to create an instance of CollectionResponseAssociatedId
            //instance = new CollectionResponseAssociatedId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionResponseAssociatedId
        /// </summary>
        [Fact]
        public void CollectionResponseAssociatedIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" CollectionResponseAssociatedId
            //Assert.IsType<CollectionResponseAssociatedId>(instance);
        }

        /// <summary>
        /// Test the property 'Paging'
        /// </summary>
        [Fact]
        public void PagingTest()
        {
            // TODO unit test for the property 'Paging'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
