/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing FilterGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FilterGroupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FilterGroup
        //private FilterGroup instance;

        public FilterGroupTests()
        {
            // TODO uncomment below to create an instance of FilterGroup
            //instance = new FilterGroup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterGroup
        /// </summary>
        [Fact]
        public void FilterGroupInstanceTest()
        {
            // TODO uncomment below to test "IsType" FilterGroup
            //Assert.IsType<FilterGroup>(instance);
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
    }
}
