/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing Paging
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PagingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Paging
        //private Paging instance;

        public PagingTests()
        {
            // TODO uncomment below to create an instance of Paging
            //instance = new Paging();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Paging
        /// </summary>
        [Fact]
        public void PagingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Paging
            //Assert.IsType<Paging>(instance);
        }

        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

        /// <summary>
        /// Test the property 'Prev'
        /// </summary>
        [Fact]
        public void PrevTest()
        {
            // TODO unit test for the property 'Prev'
        }
    }
}
