/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing PreviousPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreviousPageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreviousPage
        //private PreviousPage instance;

        public PreviousPageTests()
        {
            // TODO uncomment below to create an instance of PreviousPage
            //instance = new PreviousPage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreviousPage
        /// </summary>
        [Fact]
        public void PreviousPageInstanceTest()
        {
            // TODO uncomment below to test "IsType" PreviousPage
            //Assert.IsType<PreviousPage>(instance);
        }

        /// <summary>
        /// Test the property 'Before'
        /// </summary>
        [Fact]
        public void BeforeTest()
        {
            // TODO unit test for the property 'Before'
        }

        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }
    }
}
