/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing PublicGdprDeleteInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicGdprDeleteInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicGdprDeleteInput
        //private PublicGdprDeleteInput instance;

        public PublicGdprDeleteInputTests()
        {
            // TODO uncomment below to create an instance of PublicGdprDeleteInput
            //instance = new PublicGdprDeleteInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicGdprDeleteInput
        /// </summary>
        [Fact]
        public void PublicGdprDeleteInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicGdprDeleteInput
            //Assert.IsType<PublicGdprDeleteInput>(instance);
        }

        /// <summary>
        /// Test the property 'IdProperty'
        /// </summary>
        [Fact]
        public void IdPropertyTest()
        {
            // TODO unit test for the property 'IdProperty'
        }

        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Fact]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
    }
}
