/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing PublicObjectId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicObjectIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicObjectId
        //private PublicObjectId instance;

        public PublicObjectIdTests()
        {
            // TODO uncomment below to create an instance of PublicObjectId
            //instance = new PublicObjectId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicObjectId
        /// </summary>
        [Fact]
        public void PublicObjectIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicObjectId
            //Assert.IsType<PublicObjectId>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
