/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing PublicMergeInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicMergeInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicMergeInput
        //private PublicMergeInput instance;

        public PublicMergeInputTests()
        {
            // TODO uncomment below to create an instance of PublicMergeInput
            //instance = new PublicMergeInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicMergeInput
        /// </summary>
        [Fact]
        public void PublicMergeInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicMergeInput
            //Assert.IsType<PublicMergeInput>(instance);
        }

        /// <summary>
        /// Test the property 'ObjectIdToMerge'
        /// </summary>
        [Fact]
        public void ObjectIdToMergeTest()
        {
            // TODO unit test for the property 'ObjectIdToMerge'
        }

        /// <summary>
        /// Test the property 'PrimaryObjectId'
        /// </summary>
        [Fact]
        public void PrimaryObjectIdTest()
        {
            // TODO unit test for the property 'PrimaryObjectId'
        }
    }
}
