/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing PublicAssociationsForObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicAssociationsForObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicAssociationsForObject
        //private PublicAssociationsForObject instance;

        public PublicAssociationsForObjectTests()
        {
            // TODO uncomment below to create an instance of PublicAssociationsForObject
            //instance = new PublicAssociationsForObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicAssociationsForObject
        /// </summary>
        [Fact]
        public void PublicAssociationsForObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicAssociationsForObject
            //Assert.IsType<PublicAssociationsForObject>(instance);
        }

        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Fact]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
    }
}
