/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing PublicObjectSearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicObjectSearchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicObjectSearchRequest
        //private PublicObjectSearchRequest instance;

        public PublicObjectSearchRequestTests()
        {
            // TODO uncomment below to create an instance of PublicObjectSearchRequest
            //instance = new PublicObjectSearchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicObjectSearchRequest
        /// </summary>
        [Fact]
        public void PublicObjectSearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicObjectSearchRequest
            //Assert.IsType<PublicObjectSearchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'After'
        /// </summary>
        [Fact]
        public void AfterTest()
        {
            // TODO unit test for the property 'After'
        }

        /// <summary>
        /// Test the property 'Sorts'
        /// </summary>
        [Fact]
        public void SortsTest()
        {
            // TODO unit test for the property 'Sorts'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'FilterGroups'
        /// </summary>
        [Fact]
        public void FilterGroupsTest()
        {
            // TODO unit test for the property 'FilterGroups'
        }
    }
}
