/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing SimplePublicObjectInputForCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimplePublicObjectInputForCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimplePublicObjectInputForCreate
        //private SimplePublicObjectInputForCreate instance;

        public SimplePublicObjectInputForCreateTests()
        {
            // TODO uncomment below to create an instance of SimplePublicObjectInputForCreate
            //instance = new SimplePublicObjectInputForCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimplePublicObjectInputForCreate
        /// </summary>
        [Fact]
        public void SimplePublicObjectInputForCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimplePublicObjectInputForCreate
            //Assert.IsType<SimplePublicObjectInputForCreate>(instance);
        }

        /// <summary>
        /// Test the property 'Associations'
        /// </summary>
        [Fact]
        public void AssociationsTest()
        {
            // TODO unit test for the property 'Associations'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
    }
}
