/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing SimplePublicObjectWithAssociations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimplePublicObjectWithAssociationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimplePublicObjectWithAssociations
        //private SimplePublicObjectWithAssociations instance;

        public SimplePublicObjectWithAssociationsTests()
        {
            // TODO uncomment below to create an instance of SimplePublicObjectWithAssociations
            //instance = new SimplePublicObjectWithAssociations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimplePublicObjectWithAssociations
        /// </summary>
        [Fact]
        public void SimplePublicObjectWithAssociationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimplePublicObjectWithAssociations
            //Assert.IsType<SimplePublicObjectWithAssociations>(instance);
        }

        /// <summary>
        /// Test the property 'Associations'
        /// </summary>
        [Fact]
        public void AssociationsTest()
        {
            // TODO unit test for the property 'Associations'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Archived'
        /// </summary>
        [Fact]
        public void ArchivedTest()
        {
            // TODO unit test for the property 'Archived'
        }

        /// <summary>
        /// Test the property 'ArchivedAt'
        /// </summary>
        [Fact]
        public void ArchivedAtTest()
        {
            // TODO unit test for the property 'ArchivedAt'
        }

        /// <summary>
        /// Test the property 'PropertiesWithHistory'
        /// </summary>
        [Fact]
        public void PropertiesWithHistoryTest()
        {
            // TODO unit test for the property 'PropertiesWithHistory'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
