/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using rolloutHubspot.Model;
using rolloutHubspot.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace rolloutHubspot.Test.Model
{
    /// <summary>
    ///  Class for testing SimplePublicObjectBatchInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimplePublicObjectBatchInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimplePublicObjectBatchInput
        //private SimplePublicObjectBatchInput instance;

        public SimplePublicObjectBatchInputTests()
        {
            // TODO uncomment below to create an instance of SimplePublicObjectBatchInput
            //instance = new SimplePublicObjectBatchInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimplePublicObjectBatchInput
        /// </summary>
        [Fact]
        public void SimplePublicObjectBatchInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimplePublicObjectBatchInput
            //Assert.IsType<SimplePublicObjectBatchInput>(instance);
        }

        /// <summary>
        /// Test the property 'IdProperty'
        /// </summary>
        [Fact]
        public void IdPropertyTest()
        {
            // TODO unit test for the property 'IdProperty'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
    }
}
