/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using rolloutHubspot.Client;
using rolloutHubspot.Api;
// uncomment below to import models
//using rolloutHubspot.Model;

namespace rolloutHubspot.Test.Api
{
    /// <summary>
    ///  Class for testing BasicApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BasicApiTests : IDisposable
    {
        private BasicApi instance;

        public BasicApiTests()
        {
            instance = new BasicApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BasicApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BasicApi
            //Assert.IsType<BasicApi>(instance);
        }

        /// <summary>
        /// Test DeleteCrmV3ObjectsContactsContactIdArchive
        /// </summary>
        [Fact]
        public void DeleteCrmV3ObjectsContactsContactIdArchiveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contactId = null;
            //instance.DeleteCrmV3ObjectsContactsContactIdArchive(contactId);
        }

        /// <summary>
        /// Test GetCrmV3ObjectsContactsContactIdGetById
        /// </summary>
        [Fact]
        public void GetCrmV3ObjectsContactsContactIdGetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contactId = null;
            //List<string>? properties = null;
            //List<string>? propertiesWithHistory = null;
            //List<string>? associations = null;
            //bool? archived = null;
            //var response = instance.GetCrmV3ObjectsContactsContactIdGetById(contactId, properties, propertiesWithHistory, associations, archived);
            //Assert.IsType<SimplePublicObjectWithAssociations>(response);
        }

        /// <summary>
        /// Test GetCrmV3ObjectsContactsGetPage
        /// </summary>
        [Fact]
        public void GetCrmV3ObjectsContactsGetPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? after = null;
            //List<string>? properties = null;
            //List<string>? propertiesWithHistory = null;
            //List<string>? associations = null;
            //bool? archived = null;
            //var response = instance.GetCrmV3ObjectsContactsGetPage(limit, after, properties, propertiesWithHistory, associations, archived);
            //Assert.IsType<CollectionResponseSimplePublicObjectWithAssociationsForwardPaging>(response);
        }

        /// <summary>
        /// Test PatchCrmV3ObjectsContactsContactIdUpdate
        /// </summary>
        [Fact]
        public void PatchCrmV3ObjectsContactsContactIdUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contactId = null;
            //SimplePublicObjectInput simplePublicObjectInput = null;
            //var response = instance.PatchCrmV3ObjectsContactsContactIdUpdate(contactId, simplePublicObjectInput);
            //Assert.IsType<SimplePublicObject>(response);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsContactsCreate
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsContactsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SimplePublicObjectInputForCreate simplePublicObjectInputForCreate = null;
            //var response = instance.PostCrmV3ObjectsContactsCreate(simplePublicObjectInputForCreate);
            //Assert.IsType<SimplePublicObject>(response);
        }
    }
}
