/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using rolloutHubspot.Client;
using rolloutHubspot.Api;
// uncomment below to import models
//using rolloutHubspot.Model;

namespace rolloutHubspot.Test.Api
{
    /// <summary>
    ///  Class for testing BatchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BatchApiTests : IDisposable
    {
        private BatchApi instance;

        public BatchApiTests()
        {
            instance = new BatchApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BatchApi
            //Assert.IsType<BatchApi>(instance);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsContactsBatchArchiveArchive
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsContactsBatchArchiveArchiveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BatchInputSimplePublicObjectId batchInputSimplePublicObjectId = null;
            //instance.PostCrmV3ObjectsContactsBatchArchiveArchive(batchInputSimplePublicObjectId);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsContactsBatchCreateCreate
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsContactsBatchCreateCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate = null;
            //var response = instance.PostCrmV3ObjectsContactsBatchCreateCreate(batchInputSimplePublicObjectInputForCreate);
            //Assert.IsType<BatchResponseSimplePublicObject>(response);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsContactsBatchReadRead
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsContactsBatchReadReadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId = null;
            //bool? archived = null;
            //var response = instance.PostCrmV3ObjectsContactsBatchReadRead(batchReadInputSimplePublicObjectId, archived);
            //Assert.IsType<BatchResponseSimplePublicObject>(response);
        }

        /// <summary>
        /// Test PostCrmV3ObjectsContactsBatchUpdateUpdate
        /// </summary>
        [Fact]
        public void PostCrmV3ObjectsContactsBatchUpdateUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput = null;
            //var response = instance.PostCrmV3ObjectsContactsBatchUpdateUpdate(batchInputSimplePublicObjectBatchInput);
            //Assert.IsType<BatchResponseSimplePublicObject>(response);
        }
    }
}
