/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// BatchReadInputSimplePublicObjectId
    /// </summary>
    [DataContract(Name = "BatchReadInputSimplePublicObjectId")]
    public partial class BatchReadInputSimplePublicObjectId : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchReadInputSimplePublicObjectId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchReadInputSimplePublicObjectId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchReadInputSimplePublicObjectId" /> class.
        /// </summary>
        /// <param name="propertiesWithHistory">propertiesWithHistory (required).</param>
        /// <param name="idProperty">idProperty.</param>
        /// <param name="inputs">inputs (required).</param>
        /// <param name="properties">properties (required).</param>
        public BatchReadInputSimplePublicObjectId(List<string> propertiesWithHistory = default(List<string>), string idProperty = default(string), List<SimplePublicObjectId> inputs = default(List<SimplePublicObjectId>), List<string> properties = default(List<string>))
        {
            // to ensure "propertiesWithHistory" is required (not null)
            if (propertiesWithHistory == null)
            {
                throw new ArgumentNullException("propertiesWithHistory is a required property for BatchReadInputSimplePublicObjectId and cannot be null");
            }
            this.PropertiesWithHistory = propertiesWithHistory;
            // to ensure "inputs" is required (not null)
            if (inputs == null)
            {
                throw new ArgumentNullException("inputs is a required property for BatchReadInputSimplePublicObjectId and cannot be null");
            }
            this.Inputs = inputs;
            // to ensure "properties" is required (not null)
            if (properties == null)
            {
                throw new ArgumentNullException("properties is a required property for BatchReadInputSimplePublicObjectId and cannot be null");
            }
            this.Properties = properties;
            this.IdProperty = idProperty;
        }

        /// <summary>
        /// Gets or Sets PropertiesWithHistory
        /// </summary>
        [DataMember(Name = "propertiesWithHistory", IsRequired = true, EmitDefaultValue = true)]
        public List<string> PropertiesWithHistory { get; set; }

        /// <summary>
        /// Gets or Sets IdProperty
        /// </summary>
        [DataMember(Name = "idProperty", EmitDefaultValue = false)]
        public string IdProperty { get; set; }

        /// <summary>
        /// Gets or Sets Inputs
        /// </summary>
        [DataMember(Name = "inputs", IsRequired = true, EmitDefaultValue = true)]
        public List<SimplePublicObjectId> Inputs { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Properties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchReadInputSimplePublicObjectId {\n");
            sb.Append("  PropertiesWithHistory: ").Append(PropertiesWithHistory).Append("\n");
            sb.Append("  IdProperty: ").Append(IdProperty).Append("\n");
            sb.Append("  Inputs: ").Append(Inputs).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
