/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// Error
    /// </summary>
    [DataContract(Name = "Error")]
    public partial class Error : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Error" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Error() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Error" /> class.
        /// </summary>
        /// <param name="subCategory">A specific category that contains more specific detail about the error.</param>
        /// <param name="context">Context about the error condition.</param>
        /// <param name="correlationId">A unique identifier for the request. Include this value with any error reports or support tickets (required).</param>
        /// <param name="links">A map of link names to associated URIs containing documentation about the error or recommended remediation steps.</param>
        /// <param name="message">A human readable message describing the error along with remediation steps where appropriate (required).</param>
        /// <param name="category">The error category (required).</param>
        /// <param name="errors">further information about the error.</param>
        public Error(string subCategory = default(string), Dictionary<string, List<string>> context = default(Dictionary<string, List<string>>), Guid correlationId = default(Guid), Dictionary<string, string> links = default(Dictionary<string, string>), string message = default(string), string category = default(string), List<ErrorDetail> errors = default(List<ErrorDetail>))
        {
            this.CorrelationId = correlationId;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for Error and cannot be null");
            }
            this.Message = message;
            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new ArgumentNullException("category is a required property for Error and cannot be null");
            }
            this.Category = category;
            this.SubCategory = subCategory;
            this.Context = context;
            this.Links = links;
            this.Errors = errors;
        }

        /// <summary>
        /// A specific category that contains more specific detail about the error
        /// </summary>
        /// <value>A specific category that contains more specific detail about the error</value>
        [DataMember(Name = "subCategory", EmitDefaultValue = false)]
        public string SubCategory { get; set; }

        /// <summary>
        /// Context about the error condition
        /// </summary>
        /// <value>Context about the error condition</value>
        /// <example>{&quot;missingScopes&quot;:[&quot;scope1&quot;,&quot;scope2&quot;],&quot;invalidPropertyName&quot;:[&quot;propertyValue&quot;]}</example>
        [DataMember(Name = "context", EmitDefaultValue = false)]
        public Dictionary<string, List<string>> Context { get; set; }

        /// <summary>
        /// A unique identifier for the request. Include this value with any error reports or support tickets
        /// </summary>
        /// <value>A unique identifier for the request. Include this value with any error reports or support tickets</value>
        /// <example>aeb5f871-7f07-4993-9211-075dc63e7cbf</example>
        [DataMember(Name = "correlationId", IsRequired = true, EmitDefaultValue = true)]
        public Guid CorrelationId { get; set; }

        /// <summary>
        /// A map of link names to associated URIs containing documentation about the error or recommended remediation steps
        /// </summary>
        /// <value>A map of link names to associated URIs containing documentation about the error or recommended remediation steps</value>
        /// <example>{&quot;knowledge-base&quot;:&quot;https://www.hubspot.com/products/service/knowledge-base&quot;}</example>
        [DataMember(Name = "links", EmitDefaultValue = false)]
        public Dictionary<string, string> Links { get; set; }

        /// <summary>
        /// A human readable message describing the error along with remediation steps where appropriate
        /// </summary>
        /// <value>A human readable message describing the error along with remediation steps where appropriate</value>
        /// <example>Invalid input (details will vary based on the error)</example>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// The error category
        /// </summary>
        /// <value>The error category</value>
        /// <example>VALIDATION_ERROR</example>
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = true)]
        public string Category { get; set; }

        /// <summary>
        /// further information about the error
        /// </summary>
        /// <value>further information about the error</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<ErrorDetail> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Error {\n");
            sb.Append("  SubCategory: ").Append(SubCategory).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("  CorrelationId: ").Append(CorrelationId).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
