/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// NextPage
    /// </summary>
    [DataContract(Name = "NextPage")]
    public partial class NextPage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NextPage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NextPage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NextPage" /> class.
        /// </summary>
        /// <param name="link">link.</param>
        /// <param name="after">after (required).</param>
        public NextPage(string link = default(string), string after = default(string))
        {
            // to ensure "after" is required (not null)
            if (after == null)
            {
                throw new ArgumentNullException("after is a required property for NextPage and cannot be null");
            }
            this.After = after;
            this.Link = link;
        }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        /// <example>?after&#x3D;NTI1Cg%3D%3D</example>
        [DataMember(Name = "link", EmitDefaultValue = false)]
        public string Link { get; set; }

        /// <summary>
        /// Gets or Sets After
        /// </summary>
        /// <example>NTI1Cg%3D%3D</example>
        [DataMember(Name = "after", IsRequired = true, EmitDefaultValue = true)]
        public string After { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NextPage {\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  After: ").Append(After).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
