/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// PublicObjectSearchRequest
    /// </summary>
    [DataContract(Name = "PublicObjectSearchRequest")]
    public partial class PublicObjectSearchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicObjectSearchRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicObjectSearchRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicObjectSearchRequest" /> class.
        /// </summary>
        /// <param name="query">query.</param>
        /// <param name="limit">limit (required).</param>
        /// <param name="after">after (required).</param>
        /// <param name="sorts">sorts (required).</param>
        /// <param name="properties">properties (required).</param>
        /// <param name="filterGroups">filterGroups (required).</param>
        public PublicObjectSearchRequest(string query = default(string), int limit = default(int), string after = default(string), List<string> sorts = default(List<string>), List<string> properties = default(List<string>), List<FilterGroup> filterGroups = default(List<FilterGroup>))
        {
            this.Limit = limit;
            // to ensure "after" is required (not null)
            if (after == null)
            {
                throw new ArgumentNullException("after is a required property for PublicObjectSearchRequest and cannot be null");
            }
            this.After = after;
            // to ensure "sorts" is required (not null)
            if (sorts == null)
            {
                throw new ArgumentNullException("sorts is a required property for PublicObjectSearchRequest and cannot be null");
            }
            this.Sorts = sorts;
            // to ensure "properties" is required (not null)
            if (properties == null)
            {
                throw new ArgumentNullException("properties is a required property for PublicObjectSearchRequest and cannot be null");
            }
            this.Properties = properties;
            // to ensure "filterGroups" is required (not null)
            if (filterGroups == null)
            {
                throw new ArgumentNullException("filterGroups is a required property for PublicObjectSearchRequest and cannot be null");
            }
            this.FilterGroups = filterGroups;
            this.Query = query;
        }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [DataMember(Name = "query", EmitDefaultValue = false)]
        public string Query { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// Gets or Sets After
        /// </summary>
        [DataMember(Name = "after", IsRequired = true, EmitDefaultValue = true)]
        public string After { get; set; }

        /// <summary>
        /// Gets or Sets Sorts
        /// </summary>
        [DataMember(Name = "sorts", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Sorts { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Properties { get; set; }

        /// <summary>
        /// Gets or Sets FilterGroups
        /// </summary>
        [DataMember(Name = "filterGroups", IsRequired = true, EmitDefaultValue = true)]
        public List<FilterGroup> FilterGroups { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicObjectSearchRequest {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  After: ").Append(After).Append("\n");
            sb.Append("  Sorts: ").Append(Sorts).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  FilterGroups: ").Append(FilterGroups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
