/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// PublicMergeInput
    /// </summary>
    [DataContract(Name = "PublicMergeInput")]
    public partial class PublicMergeInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicMergeInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicMergeInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicMergeInput" /> class.
        /// </summary>
        /// <param name="objectIdToMerge">objectIdToMerge (required).</param>
        /// <param name="primaryObjectId">primaryObjectId (required).</param>
        public PublicMergeInput(string objectIdToMerge = default(string), string primaryObjectId = default(string))
        {
            // to ensure "objectIdToMerge" is required (not null)
            if (objectIdToMerge == null)
            {
                throw new ArgumentNullException("objectIdToMerge is a required property for PublicMergeInput and cannot be null");
            }
            this.ObjectIdToMerge = objectIdToMerge;
            // to ensure "primaryObjectId" is required (not null)
            if (primaryObjectId == null)
            {
                throw new ArgumentNullException("primaryObjectId is a required property for PublicMergeInput and cannot be null");
            }
            this.PrimaryObjectId = primaryObjectId;
        }

        /// <summary>
        /// Gets or Sets ObjectIdToMerge
        /// </summary>
        [DataMember(Name = "objectIdToMerge", IsRequired = true, EmitDefaultValue = true)]
        public string ObjectIdToMerge { get; set; }

        /// <summary>
        /// Gets or Sets PrimaryObjectId
        /// </summary>
        [DataMember(Name = "primaryObjectId", IsRequired = true, EmitDefaultValue = true)]
        public string PrimaryObjectId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicMergeInput {\n");
            sb.Append("  ObjectIdToMerge: ").Append(ObjectIdToMerge).Append("\n");
            sb.Append("  PrimaryObjectId: ").Append(PrimaryObjectId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
