/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// PublicGdprDeleteInput
    /// </summary>
    [DataContract(Name = "PublicGdprDeleteInput")]
    public partial class PublicGdprDeleteInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicGdprDeleteInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublicGdprDeleteInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicGdprDeleteInput" /> class.
        /// </summary>
        /// <param name="idProperty">idProperty.</param>
        /// <param name="objectId">objectId (required).</param>
        public PublicGdprDeleteInput(string idProperty = default(string), string objectId = default(string))
        {
            // to ensure "objectId" is required (not null)
            if (objectId == null)
            {
                throw new ArgumentNullException("objectId is a required property for PublicGdprDeleteInput and cannot be null");
            }
            this.ObjectId = objectId;
            this.IdProperty = idProperty;
        }

        /// <summary>
        /// Gets or Sets IdProperty
        /// </summary>
        [DataMember(Name = "idProperty", EmitDefaultValue = false)]
        public string IdProperty { get; set; }

        /// <summary>
        /// Gets or Sets ObjectId
        /// </summary>
        [DataMember(Name = "objectId", IsRequired = true, EmitDefaultValue = true)]
        public string ObjectId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicGdprDeleteInput {\n");
            sb.Append("  IdProperty: ").Append(IdProperty).Append("\n");
            sb.Append("  ObjectId: ").Append(ObjectId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
