/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// SimplePublicObject
    /// </summary>
    [DataContract(Name = "SimplePublicObject")]
    public partial class SimplePublicObject : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimplePublicObject" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SimplePublicObject() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SimplePublicObject" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="archived">archived.</param>
        /// <param name="archivedAt">archivedAt.</param>
        /// <param name="propertiesWithHistory">propertiesWithHistory.</param>
        /// <param name="id">id (required).</param>
        /// <param name="properties">properties (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public SimplePublicObject(DateTime createdAt = default(DateTime), bool archived = default(bool), DateTime archivedAt = default(DateTime), Dictionary<string, List<ValueWithTimestamp>> propertiesWithHistory = default(Dictionary<string, List<ValueWithTimestamp>>), string id = default(string), Dictionary<string, string> properties = default(Dictionary<string, string>), DateTime updatedAt = default(DateTime))
        {
            this.CreatedAt = createdAt;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SimplePublicObject and cannot be null");
            }
            this.Id = id;
            // to ensure "properties" is required (not null)
            if (properties == null)
            {
                throw new ArgumentNullException("properties is a required property for SimplePublicObject and cannot be null");
            }
            this.Properties = properties;
            this.UpdatedAt = updatedAt;
            this.Archived = archived;
            this.ArchivedAt = archivedAt;
            this.PropertiesWithHistory = propertiesWithHistory;
        }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Archived
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "archived", EmitDefaultValue = true)]
        public bool Archived { get; set; }

        /// <summary>
        /// Gets or Sets ArchivedAt
        /// </summary>
        [DataMember(Name = "archivedAt", EmitDefaultValue = false)]
        public DateTime ArchivedAt { get; set; }

        /// <summary>
        /// Gets or Sets PropertiesWithHistory
        /// </summary>
        [DataMember(Name = "propertiesWithHistory", EmitDefaultValue = false)]
        public Dictionary<string, List<ValueWithTimestamp>> PropertiesWithHistory { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>512</example>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        /// <example>{&quot;property_date&quot;:&quot;1572480000000&quot;,&quot;property_radio&quot;:&quot;option_1&quot;,&quot;property_number&quot;:&quot;17&quot;,&quot;property_string&quot;:&quot;value&quot;,&quot;property_checkbox&quot;:&quot;false&quot;,&quot;property_dropdown&quot;:&quot;choice_b&quot;,&quot;property_multiple_checkboxes&quot;:&quot;chocolate;strawberry&quot;}</example>
        [DataMember(Name = "properties", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimplePublicObject {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Archived: ").Append(Archived).Append("\n");
            sb.Append("  ArchivedAt: ").Append(ArchivedAt).Append("\n");
            sb.Append("  PropertiesWithHistory: ").Append(PropertiesWithHistory).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
