/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = rolloutHubspot.Client.OpenAPIDateConverter;

namespace rolloutHubspot.Model
{
    /// <summary>
    /// SimplePublicObjectBatchInput
    /// </summary>
    [DataContract(Name = "SimplePublicObjectBatchInput")]
    public partial class SimplePublicObjectBatchInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimplePublicObjectBatchInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SimplePublicObjectBatchInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SimplePublicObjectBatchInput" /> class.
        /// </summary>
        /// <param name="idProperty">idProperty.</param>
        /// <param name="id">id (required).</param>
        /// <param name="properties">properties (required).</param>
        public SimplePublicObjectBatchInput(string idProperty = default(string), string id = default(string), Dictionary<string, string> properties = default(Dictionary<string, string>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for SimplePublicObjectBatchInput and cannot be null");
            }
            this.Id = id;
            // to ensure "properties" is required (not null)
            if (properties == null)
            {
                throw new ArgumentNullException("properties is a required property for SimplePublicObjectBatchInput and cannot be null");
            }
            this.Properties = properties;
            this.IdProperty = idProperty;
        }

        /// <summary>
        /// Gets or Sets IdProperty
        /// </summary>
        /// <example>my_unique_property_name</example>
        [DataMember(Name = "idProperty", EmitDefaultValue = false)]
        public string IdProperty { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        /// <example>{&quot;email&quot;:&quot;bcooper@biglytics.net&quot;,&quot;phone&quot;:&quot;(877) 929-0687&quot;,&quot;company&quot;:&quot;Biglytics&quot;,&quot;website&quot;:&quot;biglytics.net&quot;,&quot;lastname&quot;:&quot;Cooper&quot;,&quot;firstname&quot;:&quot;Bryan&quot;}</example>
        [DataMember(Name = "properties", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> Properties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimplePublicObjectBatchInput {\n");
            sb.Append("  IdProperty: ").Append(IdProperty).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
