/*
 * Contacts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using rolloutHubspot.Client;
using rolloutHubspot.Client.Auth;
using rolloutHubspot.Model;

namespace rolloutHubspot.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Archive a batch of contacts by ID
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void PostCrmV3ObjectsContactsBatchArchiveArchive(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0);

        /// <summary>
        /// Archive a batch of contacts by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostCrmV3ObjectsContactsBatchArchiveArchiveWithHttpInfo(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0);
        /// <summary>
        /// Create a batch of contacts
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponseSimplePublicObject</returns>
        BatchResponseSimplePublicObject PostCrmV3ObjectsContactsBatchCreateCreate(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0);

        /// <summary>
        /// Create a batch of contacts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponseSimplePublicObject</returns>
        ApiResponse<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchCreateCreateWithHttpInfo(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0);
        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponseSimplePublicObject</returns>
        BatchResponseSimplePublicObject PostCrmV3ObjectsContactsBatchReadRead(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponseSimplePublicObject</returns>
        ApiResponse<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchReadReadWithHttpInfo(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0);
        /// <summary>
        /// Update a batch of contacts
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponseSimplePublicObject</returns>
        BatchResponseSimplePublicObject PostCrmV3ObjectsContactsBatchUpdateUpdate(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0);

        /// <summary>
        /// Update a batch of contacts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponseSimplePublicObject</returns>
        ApiResponse<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchUpdateUpdateWithHttpInfo(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Archive a batch of contacts by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostCrmV3ObjectsContactsBatchArchiveArchiveAsync(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Archive a batch of contacts by ID
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostCrmV3ObjectsContactsBatchArchiveArchiveWithHttpInfoAsync(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create a batch of contacts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponseSimplePublicObject</returns>
        System.Threading.Tasks.Task<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchCreateCreateAsync(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a batch of contacts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponseSimplePublicObject)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchResponseSimplePublicObject>> PostCrmV3ObjectsContactsBatchCreateCreateWithHttpInfoAsync(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponseSimplePublicObject</returns>
        System.Threading.Tasks.Task<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchReadReadAsync(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponseSimplePublicObject)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchResponseSimplePublicObject>> PostCrmV3ObjectsContactsBatchReadReadWithHttpInfoAsync(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update a batch of contacts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponseSimplePublicObject</returns>
        System.Threading.Tasks.Task<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchUpdateUpdateAsync(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update a batch of contacts
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponseSimplePublicObject)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchResponseSimplePublicObject>> PostCrmV3ObjectsContactsBatchUpdateUpdateWithHttpInfoAsync(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchApi : IBatchApiSync, IBatchApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BatchApi : IBatchApi
    {
        private rolloutHubspot.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchApi(string basePath)
        {
            this.Configuration = rolloutHubspot.Client.Configuration.MergeConfigurations(
                rolloutHubspot.Client.GlobalConfiguration.Instance,
                new rolloutHubspot.Client.Configuration { BasePath = basePath }
            );
            this.Client = new rolloutHubspot.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new rolloutHubspot.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = rolloutHubspot.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BatchApi(rolloutHubspot.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = rolloutHubspot.Client.Configuration.MergeConfigurations(
                rolloutHubspot.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new rolloutHubspot.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new rolloutHubspot.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = rolloutHubspot.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BatchApi(rolloutHubspot.Client.ISynchronousClient client, rolloutHubspot.Client.IAsynchronousClient asyncClient, rolloutHubspot.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = rolloutHubspot.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public rolloutHubspot.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public rolloutHubspot.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public rolloutHubspot.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public rolloutHubspot.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Archive a batch of contacts by ID 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void PostCrmV3ObjectsContactsBatchArchiveArchive(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0)
        {
            PostCrmV3ObjectsContactsBatchArchiveArchiveWithHttpInfo(batchInputSimplePublicObjectId);
        }

        /// <summary>
        /// Archive a batch of contacts by ID 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public rolloutHubspot.Client.ApiResponse<Object> PostCrmV3ObjectsContactsBatchArchiveArchiveWithHttpInfo(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0)
        {
            // verify the required parameter 'batchInputSimplePublicObjectId' is set
            if (batchInputSimplePublicObjectId == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchInputSimplePublicObjectId' when calling BatchApi->PostCrmV3ObjectsContactsBatchArchiveArchive");
            }

            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchInputSimplePublicObjectId;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchArchiveArchive";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/crm/v3/objects/contacts/batch/archive", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchArchiveArchive", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Archive a batch of contacts by ID 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostCrmV3ObjectsContactsBatchArchiveArchiveAsync(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await PostCrmV3ObjectsContactsBatchArchiveArchiveWithHttpInfoAsync(batchInputSimplePublicObjectId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Archive a batch of contacts by ID 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<rolloutHubspot.Client.ApiResponse<Object>> PostCrmV3ObjectsContactsBatchArchiveArchiveWithHttpInfoAsync(BatchInputSimplePublicObjectId batchInputSimplePublicObjectId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchInputSimplePublicObjectId' is set
            if (batchInputSimplePublicObjectId == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchInputSimplePublicObjectId' when calling BatchApi->PostCrmV3ObjectsContactsBatchArchiveArchive");
            }


            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchInputSimplePublicObjectId;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchArchiveArchive";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/crm/v3/objects/contacts/batch/archive", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchArchiveArchive", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponseSimplePublicObject</returns>
        public BatchResponseSimplePublicObject PostCrmV3ObjectsContactsBatchCreateCreate(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0)
        {
            rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> localVarResponse = PostCrmV3ObjectsContactsBatchCreateCreateWithHttpInfo(batchInputSimplePublicObjectInputForCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponseSimplePublicObject</returns>
        public rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchCreateCreateWithHttpInfo(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0)
        {
            // verify the required parameter 'batchInputSimplePublicObjectInputForCreate' is set
            if (batchInputSimplePublicObjectInputForCreate == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchInputSimplePublicObjectInputForCreate' when calling BatchApi->PostCrmV3ObjectsContactsBatchCreateCreate");
            }

            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchInputSimplePublicObjectInputForCreate;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchCreateCreate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchResponseSimplePublicObject>("/crm/v3/objects/contacts/batch/create", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchCreateCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponseSimplePublicObject</returns>
        public async System.Threading.Tasks.Task<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchCreateCreateAsync(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> localVarResponse = await PostCrmV3ObjectsContactsBatchCreateCreateWithHttpInfoAsync(batchInputSimplePublicObjectInputForCreate, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectInputForCreate"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponseSimplePublicObject)</returns>
        public async System.Threading.Tasks.Task<rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject>> PostCrmV3ObjectsContactsBatchCreateCreateWithHttpInfoAsync(BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchInputSimplePublicObjectInputForCreate' is set
            if (batchInputSimplePublicObjectInputForCreate == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchInputSimplePublicObjectInputForCreate' when calling BatchApi->PostCrmV3ObjectsContactsBatchCreateCreate");
            }


            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchInputSimplePublicObjectInputForCreate;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchCreateCreate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchResponseSimplePublicObject>("/crm/v3/objects/contacts/batch/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchCreateCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponseSimplePublicObject</returns>
        public BatchResponseSimplePublicObject PostCrmV3ObjectsContactsBatchReadRead(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0)
        {
            rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> localVarResponse = PostCrmV3ObjectsContactsBatchReadReadWithHttpInfo(batchReadInputSimplePublicObjectId, archived);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponseSimplePublicObject</returns>
        public rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchReadReadWithHttpInfo(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'batchReadInputSimplePublicObjectId' is set
            if (batchReadInputSimplePublicObjectId == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchReadInputSimplePublicObjectId' when calling BatchApi->PostCrmV3ObjectsContactsBatchReadRead");
            }

            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (archived != null)
            {
                localVarRequestOptions.QueryParameters.Add(rolloutHubspot.Client.ClientUtils.ParameterToMultiMap("", "archived", archived));
            }
            localVarRequestOptions.Data = batchReadInputSimplePublicObjectId;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchReadRead";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchResponseSimplePublicObject>("/crm/v3/objects/contacts/batch/read", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchReadRead", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponseSimplePublicObject</returns>
        public async System.Threading.Tasks.Task<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchReadReadAsync(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> localVarResponse = await PostCrmV3ObjectsContactsBatchReadReadWithHttpInfoAsync(batchReadInputSimplePublicObjectId, archived, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Read a batch of contacts by internal ID, or unique property values 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchReadInputSimplePublicObjectId"></param>
        /// <param name="archived">Whether to return only results that have been archived. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponseSimplePublicObject)</returns>
        public async System.Threading.Tasks.Task<rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject>> PostCrmV3ObjectsContactsBatchReadReadWithHttpInfoAsync(BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId, bool? archived = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchReadInputSimplePublicObjectId' is set
            if (batchReadInputSimplePublicObjectId == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchReadInputSimplePublicObjectId' when calling BatchApi->PostCrmV3ObjectsContactsBatchReadRead");
            }


            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (archived != null)
            {
                localVarRequestOptions.QueryParameters.Add(rolloutHubspot.Client.ClientUtils.ParameterToMultiMap("", "archived", archived));
            }
            localVarRequestOptions.Data = batchReadInputSimplePublicObjectId;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchReadRead";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchResponseSimplePublicObject>("/crm/v3/objects/contacts/batch/read", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchReadRead", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponseSimplePublicObject</returns>
        public BatchResponseSimplePublicObject PostCrmV3ObjectsContactsBatchUpdateUpdate(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0)
        {
            rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> localVarResponse = PostCrmV3ObjectsContactsBatchUpdateUpdateWithHttpInfo(batchInputSimplePublicObjectBatchInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponseSimplePublicObject</returns>
        public rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchUpdateUpdateWithHttpInfo(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0)
        {
            // verify the required parameter 'batchInputSimplePublicObjectBatchInput' is set
            if (batchInputSimplePublicObjectBatchInput == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchInputSimplePublicObjectBatchInput' when calling BatchApi->PostCrmV3ObjectsContactsBatchUpdateUpdate");
            }

            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchInputSimplePublicObjectBatchInput;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchUpdateUpdate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchResponseSimplePublicObject>("/crm/v3/objects/contacts/batch/update", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchUpdateUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponseSimplePublicObject</returns>
        public async System.Threading.Tasks.Task<BatchResponseSimplePublicObject> PostCrmV3ObjectsContactsBatchUpdateUpdateAsync(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject> localVarResponse = await PostCrmV3ObjectsContactsBatchUpdateUpdateWithHttpInfoAsync(batchInputSimplePublicObjectBatchInput, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update a batch of contacts 
        /// </summary>
        /// <exception cref="rolloutHubspot.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchInputSimplePublicObjectBatchInput"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponseSimplePublicObject)</returns>
        public async System.Threading.Tasks.Task<rolloutHubspot.Client.ApiResponse<BatchResponseSimplePublicObject>> PostCrmV3ObjectsContactsBatchUpdateUpdateWithHttpInfoAsync(BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchInputSimplePublicObjectBatchInput' is set
            if (batchInputSimplePublicObjectBatchInput == null)
            {
                throw new rolloutHubspot.Client.ApiException(400, "Missing required parameter 'batchInputSimplePublicObjectBatchInput' when calling BatchApi->PostCrmV3ObjectsContactsBatchUpdateUpdate");
            }


            rolloutHubspot.Client.RequestOptions localVarRequestOptions = new rolloutHubspot.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = rolloutHubspot.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = rolloutHubspot.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchInputSimplePublicObjectBatchInput;

            localVarRequestOptions.Operation = "BatchApi.PostCrmV3ObjectsContactsBatchUpdateUpdate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }
            // authentication (private_apps) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("private-app")))
            {
                localVarRequestOptions.HeaderParameters.Add("private-app", this.Configuration.GetApiKeyWithPrefix("private-app"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchResponseSimplePublicObject>("/crm/v3/objects/contacts/batch/update", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCrmV3ObjectsContactsBatchUpdateUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
